import { test, expect } from '@playwright/test'
import { selectWorkspace } from './workspace-navigation'

test('startup offers five tools; drag, zoom, move, connect and remove operate on the same graph', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('region', { name: '引导界面', exact: true })).toBeVisible()
  const library = page.getByRole('navigation', { name: '引导功能库' })
  await expect(library.getByRole('button')).toHaveCount(5)
  const canvas = page.getByLabel('流程画布', { exact: true })
  await library.getByRole('button', { name: '添加化学平衡分析' }).dragTo(canvas, { targetPosition: { x: 180, y: 160 } })
  const chemistry = page.getByRole('article', { name: '化学平衡分析', exact: true })
  await expect(chemistry).toBeVisible()
  await expect(chemistry.getByRole('button', { name: '打开化学平衡分析' })).toBeDisabled()
  await page.getByRole('button', { name: '缩小画布' }).click()
  await library.getByRole('button', { name: '添加喷管初步设计' }).dragTo(canvas, { targetPosition: { x: 600, y: 290 } })
  const nozzle = page.getByRole('article', { name: '喷管初步设计', exact: true })
  await expect(nozzle).toBeVisible()
  const canvasBox = (await canvas.boundingBox())!, nozzleBox = (await nozzle.boundingBox())!
  expect(nozzleBox.x - canvasBox.x).toBeCloseTo(600 - 124 * 0.9, 0)
  const heading = nozzle.getByRole('button', { name: '移动喷管初步设计' })
  const before = (await heading.boundingBox())!
  await page.mouse.move(before.x + 70, before.y + 20)
  await page.mouse.down()
  await page.mouse.move(before.x + 160, before.y + 65, { steps: 8 })
  await page.mouse.up()
  const after = (await heading.boundingBox())!
  expect(after.x - before.x).toBeCloseTo(90, 0)
  await heading.press('ArrowDown')
  expect((await heading.boundingBox())!.y - after.y).toBeCloseTo(18, 0)
  await chemistry.getByRole('button', { name: '化学平衡分析输出端' }).click()
  await nozzle.getByRole('button', { name: '喷管初步设计输入端' }).click()
  const link = page.getByRole('button', { name: '连接：化学平衡分析 → 喷管初步设计' })
  await expect(link).toHaveCount(1)
  await chemistry.getByRole('button', { name: '化学平衡分析输出端' }).click()
  await nozzle.getByRole('button', { name: '喷管初步设计输入端' }).click()
  await expect(page.getByText('这两个节点已连接', { exact: true })).toBeVisible()
  await link.focus()
  await link.press('Enter')
  await page.getByRole('button', { name: '删除所选连接' }).click()
  await expect(link).toHaveCount(0)
  await chemistry.getByRole('button', { name: '化学平衡分析输出端' }).click()
  await nozzle.getByRole('button', { name: '喷管初步设计输入端' }).click()
  await page.screenshot({ path: test.info().outputPath('guide-connected.png') })
  await nozzle.getByRole('button', { name: '移除喷管初步设计' }).click()
  await expect(link).toHaveCount(0)
  expect(errors).toEqual([])
})

test('opening a workspace and returning preserves the draft; startup always returns to guide', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '添加喷管初步设计' }).click()
  await page.getByRole('button', { name: '添加喷注器水力设计' }).click()
  await page.getByRole('button', { name: '喷管初步设计输出端' }).click()
  await page.getByRole('button', { name: '喷注器水力设计输入端' }).click()
  await page.getByRole('button', { name: '打开喷管初步设计' }).click()
  await expect(page.getByRole('heading', { name: '喷管初步设计', exact: true })).toBeVisible()
  await selectWorkspace(page, '引导界面')
  await expect(page.getByRole('article')).toHaveCount(2)
  await expect(page.getByRole('button', { name: '连接：喷管初步设计 → 喷注器水力设计' })).toHaveCount(1)
  await page.reload()
  await expect(page.getByRole('region', { name: '引导界面', exact: true })).toBeVisible()
  await expect(page.getByRole('article')).toHaveCount(0)
})

test('search, keyboard connection cancellation and compact layout remain usable', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: '搜索功能' }).fill('不存在')
  await expect(page.getByText('没有匹配的功能')).toBeVisible()
  await page.getByRole('textbox', { name: '搜索功能' }).fill('喷管')
  await page.getByRole('button', { name: '添加喷管初步设计' }).press('Enter')
  await page.getByRole('button', { name: '喷管初步设计输出端' }).press('Enter')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '喷管初步设计输出端' })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('textbox', { name: '搜索功能' }).fill('')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('textbox', { name: '搜索功能' })).toBeVisible()
  await page.getByRole('button', { name: '添加喷注器水力设计' }).click()
  await expect(page.getByRole('article')).toHaveCount(2)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('guide-compact.png') })
})
